#!/bin/bash

# Env Vars:
# NUM: number of instances of the job to run
# REPOSITORY: name of the image registry/namespace to get the images

# Clean up previous run
function clean() {
  set +x
  echo Cleaning...
  ibmcloud ce app delete -n anj-app -f --wto=0 > /dev/null 2>&1 || true
  ibmcloud ce jobrun delete -n anj-job -f > /dev/null 2>&1 || true
  rm -f out
}

clean
[[ "$1" == "clean" ]] && exit 0

set -ex
export REPOSITORY=${REPOSITORY:-ibmcom}
export NUM=${NUM:-10}

# First create an app based on our image
ibmcloud ce app create -n anj-app --image ${REPOSITORY}/app-n-job

# Get the URL of the app
URL=$(ibmcloud ce app get -n anj-app -o jsonpath={.status.url})

# And call it
curl -Ls $URL | tee out

if ! grep "Hello from.*app" out > /dev/null ; then
  echo "Unexpected output"
  exit 1
fi

# And now use the same image as a batch job
ibmcloud ce jobrun submit --name anj-job --ai=1-$NUM --image ${REPOSITORY}/app-n-job

# Wait for it to finish...
until ibmcloud ce jobrun get --name anj-job -o jsonpath={.status.succeeded} | grep $NUM
do
  sleep 3
done

ibmcloud ce jobrun logs --instance anj-job-1-0 | tee out

if ! grep "Hello from.*job"  out > /dev/null ; then
  echo "Missing expected outout"
  exit 1
fi

# Clean up
clean
