#!/bin/bash


IMAGE=$(ibmcloud cr images | grep "ce--fleet-inferencing" | awk '{print $1}')

if [[ "$IMAGE" != "" ]]; then 
  ibmcloud cr image-rm $(ibmcloud cr images | grep "ce--fleet-inferencing" | awk '{print $1}')
fi

REGISTRY=$(ibmcloud ce secret get -n fleet-registry-secret --output json | jq -r '.data.server')

uuid=$(uuidgen | tr '[:upper:]' '[:lower:]' | awk -F- '{print $1}')

ibmcloud ce buildrun submit --name ce--fleet-inferencing-build-${uuid} --source ./src --strategy dockerfile --image $REGISTRY/ce--fleet-inferencing-${uuid}/inferencing:latest --registry-secret fleet-registry-secret  --size xxlarge --timeout 2400 

ibmcloud ce buildrun logs -f -n ce--fleet-inferencing-build-${uuid}

# takes about ??s.
