#!/usr/bin/env bash
set -eu

truncate -s0 commands.jsonl

batch_size=10
idx=0
batch_idx=0

for f in ../../data/tutorials/inferencing/recipes/*.json; do
  idx=$(( idx + 1 ))
  if (( idx % batch_size == 0 )); then
    echo "{\"command\": \"python\", \"args\": [\"app.py\", \"/mnt/ce/data/tutorials/inferencing/batches/$batch_idx.txt\"]}" >> commands.jsonl
    batch_idx=$(( batch_idx + 1 ))
  fi

  file_in=$(basename "$f")
  file_out=${file_in%.*}.augmented.json

  # echo "batch=$batch_idx idx=$idx file=$f"
  echo "/mnt/ce/data/tutorials/inferencing/recipes/$file_in;/mnt/ce/data/result/inferencing_$file_out" >> "../../data/tutorials/inferencing/batches/$batch_idx.txt"

done

echo "{\"command\": \"python\", \"args\": [\"app.py\", \"/mnt/ce/data/tutorials/inferencing/batches/$batch_idx.txt\"]}" >> commands.jsonl
