#!/bin/bash

set -e

uuid=$(uuidgen | tr '[:upper:]' '[:lower:]' | awk -F- '{print $1}')

IMAGE=$(ibmcloud cr images | grep "ce--fleet-inferencing" | awk '{print $1}')

if [ -z "${IMAGE}" ]; then
  echo "no image found. pls build a inferencing image with ./build"
  exit -1
fi

MAX_SCALE=1
PROFILE="gx3-24x120x1l40s"
CPU=24
MEMORY=120G

echo ibmcloud code-engine experimental fleet run 
echo "  "--name "fleet-${uuid}-1" 
echo "  "--image $IMAGE 
echo "  "--tasks-from-file commands.jsonl
echo "  "--worker-profile "$PROFILE"
echo "  "--cpu $CPU
echo "  "--memory $MEMORY
echo "  "--max-scale $MAX_SCALE


ibmcloud code-engine experimental fleet run --name "fleet-${uuid}-1" --image $IMAGE --registry-secret fleet-registry-secret --worker-profile $PROFILE --max-scale $MAX_SCALE --cpu $CPU --memory $MEMORY --tasks-from-file commands.jsonl

ic ce exp fleet get -n "fleet-${uuid}-1"
