#!/bin/bash

# This will build and run all demos

set -e
for file in `find . -name run | sort` ; do (

  echo -e "\n### `dirname $file`\n"
  cd `dirname $file`

  # Skip this dir
  [[ -e ./SKIP ]] && echo "SKIPPING `dirname $file`" && continue

  # If 'build' exists, build the image(s)
  [[ -e ./build ]] && ./build

  # Run the sample
  ./run

) done

echo "All done!"
