baseURL = "https://IBM.github.io/CodeEngine/"
title = "Code Engine Dev Blog"
locale = "en-us"

# Instruct Hugo to pull the theme out of the Module pipeline
theme = "blowfish"

[module]
  # Identifies this exact repository folder as the core module workspace root
  path = "github.com/IBM/CodeEngine"
  
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"

[outputs]
  home = ["HTML", "RSS", "JSON"]
