services:
  travel-concierge-agent:
    build: ./agents/travel_concierge_agent
    image: travel-concierge-agent:0.0.1
    platform: linux/amd64
    ports:
      - "5600:5600"
    environment:
      - INFERENCE_BASE_URL=${INFERENCE_BASE_URL}
      - INFERENCE_API_KEY=${INFERENCE_API_KEY}
      - INFERENCE_MODEL_NAME=${INFERENCE_MODEL_NAME}
      - INFERENCE_PROJECT_ID=${INFERENCE_PROJECT_ID}
      - AGENT_CITY_SELECTION_URL=http://city-selection-agent:5610
      - AGENT_CITY_SELECTION_NAME=City_Selection_Expert
      - AGENT_BUDGET_PLANNER_URL=http://budget-planner-agent:5620
      - AGENT_BUDGET_PLANNER_NAME=Budget_Planner
      - AGENT_CITY_EXPERT_URL=http://city-expert-agent:5630
      - AGENT_CITY_EXPERT_NAME=City_Expert
      - AGENT_HOTEL_PLANNER_URL=http://hotel-planner-agent:5640
      - AGENT_HOTEL_PLANNER_NAME=Hotel_Planner
      - AGENT_FLIGHT_PLANNER_URL=http://flight-planner-agent:5650
      - AGENT_FLIGHT_PLANNER_NAME=Flight_Planner
      - AGENT_ITINERARY_PLANNER_URL=http://itinerary-planner-agent:5660
      - AGENT_ITINERARY_PLANNER_NAME=Itinerary_Planner

    networks:
      - travel-agency-network

  city-selection-agent:
    build: ./agents/city_selection_agent
    image: city-selection-agent:0.0.1
    platform: linux/amd64
    ports:
      - "5610:5610"
    environment:
      - INFERENCE_BASE_URL=${INFERENCE_BASE_URL}
      - INFERENCE_API_KEY=${INFERENCE_API_KEY}
      - INFERENCE_MODEL_NAME=${INFERENCE_MODEL_NAME}
      - INFERENCE_PROJECT_ID=${INFERENCE_PROJECT_ID}
    networks:
      - travel-agency-network

  budget-planner-agent:
    build: ./agents/budget_planner_agent
    image: budget-planner-agent:0.0.1
    platform: linux/amd64
    ports:
      - "5620:5620"
    environment:
      - INFERENCE_BASE_URL=${INFERENCE_BASE_URL}
      - INFERENCE_API_KEY=${INFERENCE_API_KEY}
      - INFERENCE_MODEL_NAME=${INFERENCE_MODEL_NAME}
      - INFERENCE_PROJECT_ID=${INFERENCE_PROJECT_ID}
    networks:
      - travel-agency-network

  city-expert-agent:
    build: ./agents/city_expert_agent
    image: city-expert-agent:0.0.1
    platform: linux/amd64
    ports:
      - "5630:5630"
    environment:
      - INFERENCE_BASE_URL=${INFERENCE_BASE_URL}
      - INFERENCE_API_KEY=${INFERENCE_API_KEY}
      - INFERENCE_MODEL_NAME=${INFERENCE_MODEL_NAME}
      - INFERENCE_PROJECT_ID=${INFERENCE_PROJECT_ID}
    networks:
      - travel-agency-network

  hotel-planner-agent:
    build: ./agents/hotel_planner_agent
    image: hotel-planner-agent:0.0.1
    platform: linux/amd64
    ports:
      - "5640:5640"
    environment:
      - INFERENCE_BASE_URL=${INFERENCE_BASE_URL}
      - INFERENCE_API_KEY=${INFERENCE_API_KEY}
      - INFERENCE_MODEL_NAME=${INFERENCE_MODEL_NAME}
      - INFERENCE_PROJECT_ID=${INFERENCE_PROJECT_ID}
    networks:
      - travel-agency-network

  flight-planner-agent:
    build: ./agents/flight_planner_agent
    image: flight-planner-agent:0.0.1
    platform: linux/amd64
    ports:
      - "5650:5650"
    environment:
      - INFERENCE_BASE_URL=${INFERENCE_BASE_URL}
      - INFERENCE_API_KEY=${INFERENCE_API_KEY}
      - INFERENCE_MODEL_NAME=${INFERENCE_MODEL_NAME}
      - INFERENCE_PROJECT_ID=${INFERENCE_PROJECT_ID}
    networks:
      - travel-agency-network

  itinerary-planner-agent:
    build: ./agents/itinerary_planner_agent
    image: itinerary-planner-agent:0.0.1
    platform: linux/amd64
    ports:
      - "5660:5660"
    environment:
      - INFERENCE_BASE_URL=${INFERENCE_BASE_URL}
      - INFERENCE_API_KEY=${INFERENCE_API_KEY}
      - INFERENCE_MODEL_NAME=${INFERENCE_MODEL_NAME}
      - INFERENCE_PROJECT_ID=${INFERENCE_PROJECT_ID}
    networks:
      - travel-agency-network

  chat:
    build: ./ui/chat
    image: chat:0.0.1
    platform: linux/amd64
    ports:
      - "5555:5555"
    environment:
      - AGENTS_CATALOG=http://travel-concierge-agent:5600
    networks:
      - travel-agency-network

networks:
  travel-agency-network:
    driver: bridge
