#!/bin/bash

set -e

echo "Did you upload the .txt files to COS?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) break;;
        No ) echo "exiting... run ./upload first"; exit;;
    esac
done


uuid=$(uuidgen | tr '[:upper:]' '[:lower:]' | awk -F- '{print $1}')

MAX_SCALE=4
CPU=1
MEMORY=2G
CMDS=wordcount_commands.jsonl

# construct the wordcount_commands.jsonl
# ls data/tutorials/wordcount | awk '{ printf " { \"command\":\"/bin/bash\", \"args\": [\"-c\", \"cd /mnt/ce/data; wc tutorials/wordcount/"$1" > result/wordcount_"$1"\"]}\n" }' > wordcount_commands.jsonl

echo ibmcloud code-engine experimental fleet run 
echo "  "--name "fleet-${uuid}-1"
echo "  "--image registry.access.redhat.com/ubi8/ubi-minimal:latest
echo "  "--registry-secret fleet-registry-secret
echo "  "--tasks-from-local-file $CMDS
echo "  "--cpu $CPU
echo "  "--memory $MEMORY
echo "  "--max-scale $MAX_SCALE 
echo "  "--mount-data-store /input=fleet-input-store:/wordcount
echo "  "--mount-data-store /output=fleet-output-store:/wordcount

ibmcloud code-engine beta fleet create --name "fleet-${uuid}-1" --tasks-state-store fleet-task-store --image registry.access.redhat.com/ubi8/ubi-minimal:latest --registry-secret fleet-registry-secret --max-scale $MAX_SCALE --tasks-from-local-file $CMDS --cpu $CPU --memory $MEMORY --mount-data-store /input=fleet-input-store:/wordcount --mount-data-store /output=fleet-output-store:/wordcount


