#!/bin/bash

set -e

uuid=$(uuidgen | tr '[:upper:]' '[:lower:]' | awk -F- '{print $1}')

echo ibmcloud code-engine beta fleet create 
echo "  " --name "fleet-${uuid}-1" 
echo "  " --tasks-state-store fleet-task-store
echo "  " --image registry.access.redhat.com/ubi8/ubi-minimal:latest 
echo "  " --registry-secret fleet-registry-secret 
echo "  " --command="sleep" 
echo "  " --arg "60" 
echo "  " --tasks 1 
echo "  " --max-scale 1
echo "  " --gpu l40s:1

ibmcloud code-engine beta fleet create --name "fleet-${uuid}-1" --tasks-state-store fleet-task-store --image registry.access.redhat.com/ubi8/ubi-minimal:latest --registry-secret fleet-registry-secret --worker-profile cx2-2x4 --max-scale 1 --command="sleep" --arg "60" --tasks 1 --gpu l40s:1
