#!/bin/bash

set -ex

# Replace all "CE_SUBDOMAIN" in the config file with the Code Engine subdomain (k8s ns)
# see: https://www.baeldung.com/linux/nginx-config-environment-variables
envsubst < /etc/nginx/conf.d/my-site.conf.template > /etc/nginx/conf.d/default.conf

cat /etc/nginx/conf.d/default.conf

# Now run nginx
nginx -g 'daemon off;'