#!/bin/bash

# Env Vars:
# REGISTRY: name of the image registry/namespace to get the images

# Clean up previous run
function clean() {
  set +ex
  echo Cleaning...
  (
  ibmcloud ce app delete -n hello -f --wto=0
  ) > /dev/null 2>&1
}

clean
[[ "$1" == "clean" ]] && exit 0

set -ex
export REGISTRY=${REGISTRY:-ibmcom}

# Create the app (use $REGISTRY_SECRET if defined)
ibmcloud ce app create -n hello --image ${REGISTRY}/hello

# Get the URL of the app for later use
URL=$(ibmcloud ce app get -n hello -o jsonpath={.status.url})

# Now call it
curl -Ls $URL

if ! [[ "$(curl -Ls $URL)" == "Hello World" ]]; then
  echo "Unexpected output"
  exit 1
fi

# Clean up
clean
