#!/bin/bash

# Env Vars:
# REGISTRY: name of the image registry/namespace to get the images

# Clean up previous run
function clean() {
  set +ex
  echo Cleaning...
  (
  ibmcloud ce app delete -n helloworld -f
  ibmcloud ce jobrun delete -n hi-job -f
  rm -f out
  ) > /dev/null 2>&1
}

clean
[[ "$1" == "clean" ]] && exit 0

set -ex
export REGISTRY=${REGISTRY:-ibmcom}

# Create the app
ibmcloud ce app create -n helloworld --image ${REGISTRY}/helloworld

# Get the URL of the app for later use
URL=$(ibmcloud ce app get -n helloworld -o url)

# Now call it
curl -fs $URL | tee out
[[ "${PIPESTATUS[0]}" == "0" ]]

if ! [[ "$(curl -fs ${URL} -d "Hi")" == "Hi" ]]; then
  echo "Unexpected output"
  exit 1
fi

# Since the image can be used as a job too, test it
ibmcloud ce jobrun submit --name hi-job --ai=1 --image ${REGISTRY}/helloworld \
  --wait
ibmcloud ce jobrun logs -n hi-job | tee out | grep "Hello from.*job" || exit 1

# Clean up
clean
