#!/bin/bash

# Env Vars:
# REPOSITORY: name of the image registry/namespace to store the images

set -ex
export REPOSITORY=${REPOSITORY:-ibmcom}

# Build the job image and push it
docker build -t ${REPOSITORY}/firstjob -f Dockerfile .
docker push ${REPOSITORY}/firstjob
