#!/bin/bash

# Env Vars:
# NUM: number of instances of the job to run
# REGISTRY: name of the image registry/namespace to get the images

# Clean up previous run
function clean() {
  set +ex
  echo Cleaning...
  (
  ibmcloud ce job delete -n job-job -f
  ibmcloud ce jobrun delete -n job-doit  -f
  ibmcloud ce jobrun delete -n job-doit2 -f
  rm -f out
  ) > /dev/null 2>&1
}

clean
[[ "$1" == "clean" ]] && exit 0

set -ex
export REGISTRY=${REGISTRY:-icr.io/codeengine}
export NUM=${NUM:-10}

# Create a Job definition
ibmcloud ce job create --name job-job --array-indices=1-${NUM} \
  --image ${REGISTRY}/firstjob

# Now submit the job using that definition - and wait for it to finish
ibmcloud ce jobrun submit --name job-doit --job job-job --wait

# Now submit a job w/o creating a job definition first - and wait to finish
ibmcloud ce jobrun submit --name job-doit2 --array-indices=1-${NUM} \
  --image ${REGISTRY}/firstjob --wait

# Show the stats about the job
ibmcloud ce jobrun get --name job-doit2

# Now look at a view of the logs to make sure it worked
ibmcloud ce jobrun logs --instance job-doit2-1-0 | tee out

if ! grep "Hi from"  out > /dev/null ; then
  echo "Missing expected outout"
  exit 1
fi

# Clean up
clean
