#!/bin/bash

# Env Vars:
# COS_ID: If set, specifies the full CRN of a Cloud Object Storage instance to
# use

export PROJECT_NAME=$(ibmcloud ce project current | awk '/^Name/{ print $2 }')
export PROJECT_ID=$(ibmcloud ce project get --name ${PROJECT_NAME} | \
  awk '/^ID/{ print $2 }')
export POLICY_ID=""
export BUCKET=${PROJECT_NAME}-${PROJECT_ID}

# Clean up previous run
function clean() {
  set +ex
  echo "Cleaning..."

  (
  ibmcloud ce sub cos delete -n cos-sub -f --wait=true
  if [[ -n "$POLICY_ID" ]]; then
    ibmcloud iam authorization-policy-delete $POLICY_ID --force
  fi
  ibmcloud ce job delete --name cos-job --force
  ibmcloud cos object-delete --bucket ${BUCKET} --key "README.md" --force
  ibmcloud cos bucket-delete --bucket ${BUCKET} --force
  if [[ -z "$COS_ID" ]]; then
    # Delete the COS instance unless the instance was given to us
    ibmcloud resource service-instance-delete ce-cos-event -f -q
  fi
  ) > /dev/null 2>&1
}

clean
[[ "$1" == "clean" ]] && exit 0

set -ex

CID=${COS_ID}

# Create a COS instance unless one has been specified for use
if [[ $CID == "" ]]; then
  ibmcloud resource service-instance-create ce-cos-event \
    cloud-object-storage lite global
  CID=$(ibmcloud resource service-instance ce-cos-event | \
    awk '/^ID/{ print $2 }')
fi

# Set the COS config to use this instance
ibmcloud cos config crn --crn $CID --force
ibmcloud cos config auth --method IAM

# Create IAM authorization policy so we can receive notifications from COS
POLICY_ID=$(ibmcloud iam authorization-policy-create codeengine \
 cloud-object-storage "Notifications Manager" \
 --source-service-instance-name ${PROJECT_NAME} \
 --target-service-instance-id ${CID} | awk '/^Authorization/{ print $3 }')

# Create our bucket
ibmcloud cos bucket-create --bucket ${BUCKET} --ibm-service-instance-id $CID

# Create a simple job which prints the CE_DATA
ibmcloud ce job create -n cos-job \
    --image registry.access.redhat.com/ubi8/ubi-minimal:latest \
    --arg "/bin/sh" \
    --arg "-c" \
    --arg "env | grep CE_DATA"

# Setup the COS Event Source
ibmcloud ce sub cos create -n cos-sub -d cos-job --destination-type job -b ${BUCKET}

while true ; do
  # Upload a file to COS (this will generate an event)
  ibmcloud cos object-put --bucket ${BUCKET} --key "README.md" --body README.md
  # wait some time until job gets triggered
  name=$(ibmcloud ce jobrun list | grep cos-job | head -1 | sed "s/ .*//")
  [[ -z "$name" ]] && sleep 1 && continue
  sleep 5
  ibmcloud ce jobrun logs --name $name
  break
done

# Clean up
clean
