#!/bin/bash

# Env Vars:
# REGISTRY: name of the image registry/namespace to store the images
#
# NOTE: to run this you MUST set the REGISTRY environment variable to
# your own image registry/namespace otherwise the `docker push` commands
# will fail due to an auth failure. Which means, you also need to be logged
# into that registry before you run it.

set -ex
export REGISTRY=${REGISTRY:-icr.io/codeengine}

# Build and push the image
cd ce-app/
KO_DOCKER_REPO="${REGISTRY}/ce-to-private-path/app" ko build . --bare --image-user 1001 --platform linux/amd64 --sbom=none
cd ..

# Build and push the job
cd ce-job/
docker build ${NOCACHE} -t ${REGISTRY}/ce-to-private-path/job . --platform linux/amd64
docker push ${REGISTRY}/ce-to-private-path/job
cd ..