FROM icr.io/codeengine/golang AS bootstrap
WORKDIR /go/src/
COPY . .
RUN go build -o /job job.go

# Copy the exe into a smaller base image
FROM icr.io/codeengine/ubuntu
COPY --from=bootstrap /job /job
CMD ["/job"]
