#!/bin/bash

# Env Vars:
# REGISTRY: name of the image registry/namespace to store the images
# NOCACHE: set this to "--no-cache" to turn off the Docker build cache
#
# NOTE: to run this you MUST set the REGISTRY environment variable to
# your own image registry/namespace otherwise the `docker push` commands
# will fail due to an auth failure. Which means, you also need to be logged
# into that registry before you run it.

set -ex
export REGISTRY=${REGISTRY:-icr.io/codeengine}

# Build and push the oidc-auth image
cd auth
docker build ${NOCACHE} -t ${REGISTRY}/auth-oidc-proxy/auth . --platform linux/amd64
docker push ${REGISTRY}/auth-oidc-proxy/auth
cd ..

# Build and push the nginx image
cd nginx
docker build ${NOCACHE} -t ${REGISTRY}/auth-oidc-proxy/nginx . --platform linux/amd64
docker push ${REGISTRY}/auth-oidc-proxy/nginx
cd ..

