#!/bin/bash

set -e

uuid=$(uuidgen | tr '[:upper:]' '[:lower:]' | awk -F- '{print $1}')

IMAGE=$(ibmcloud cr images | grep "ce--fleet-simulation" | awk '{print $1}')

if [ -z "${IMAGE}" ]; then
  echo "no image found. pls build a simulation image with ./build.sh"
  exit -1
fi

MAX_SCALE=24
PROFILE="mx2-4x32"
CPU=1
MEMORY=8G

# getting the automatically created registry secret, e.g. ce-auto-icr-private-<region>
REGION=$(ibmcloud target -o json | jq -r '.region.name')
REGISTRY_SECRET_NAME="ce-auto-icr-private-$REGION"

PRIVATE_IMAGE="private.$IMAGE"

echo ibmcloud code-engine fleet create --name "fleet-${uuid}-1"
echo "  " --tasks-state-store fleet-task-store \
echo "  " --subnetpool-name fleet-subnetpool \
echo "  " --image $PRIVATE_IMAGE
echo "  " --registry-secret $REGISTRY_SECRET_NAME
echo "  " --worker-profile $PROFILE
echo "  " --tasks-from-local-file commands.jsonl
echo "  " --cpu $CPU
echo "  " --memory $MEMORY
echo "  " --max-scale $MAX_SCALE
echo "  " --mount-data-store /output=fleet-output-store:/simulation

ibmcloud code-engine fleet create --name "fleet-${uuid}-1" \
--tasks-state-store fleet-task-store \
--subnetpool-name fleet-subnetpool \
--image $PRIVATE_IMAGE \
--registry-secret $REGISTRY_SECRET_NAME \
--max-scale $MAX_SCALE \
--tasks-from-local-file commands.jsonl \
--cpu $CPU \
--memory $MEMORY \
--worker-profile $PROFILE \
--mount-data-store /output=fleet-output-store:/simulation

