#!/bin/bash

# Env Vars:
# NUM: number of instances of the job to run
# REPOSITORY: name of the image registry/namespace to get the images

# Clean up previous run
function clean() {
  set +x
  echo Cleaning...
  ibmcloud ce job delete -n myjob -f > /dev/null 2>&1 || true
  ibmcloud ce jobrun delete -n myjobrun -f > /dev/null 2>&1 || true
  ibmcloud resource service-instance-delete mydb -f > /dev/null 2>&1 || true
  rm -f out
}

clean

[[ "$1" == "clean" ]] && exit 0

set -ex
export REPOSITORY=${REPOSITORY:-ibmcom}
export NUM=${COUNT:-10}

# Create an instance of DB2
ibmcloud resource service-instance-create mydb dashdb-for-transactions free us-south

# Create a Job definition
ibmcloud ce job create --name myjob --array-indices=1-${NUM} \
  --image ${REPOSITORY}/bind-job

# Bind the service instance to the job
ibmcloud ce job bind --name myjob --service-instance mydb

# Now submit the job using that definition
ibmcloud ce jobrun submit --name myrun --job myjob

# Wait for it to finish...
until ibmcloud ce jobrun get --name myrun -o jsonpath={.status.succeeded} | grep $NUM
do
  sleep 3
done

# Now look at a view of the logs to make sure it worked
ibmcloud ce jobrun logs --instance myrun-1-0 | tee out

if ! grep VCAP_SERVICES out > /dev/null ; then
  echo "Missing VCAP_SERVICES in App's env vars"
  exit 1
fi

# Clean up
clean
