#!/bin/bash

# Env Vars:
# REGISTRY: name of the image registry/namespace to get the images

# Clean up previous run
function clean() {
  set +ex
  echo Cleaning...
  (
  ibmcloud ce sub cron delete -n cron-sub -f --wait=true
  ibmcloud ce app delete -n cron-app -f
  rm -f out
  ) > /dev/null 2>&1
}

clean
[[ "$1" == "clean" ]] && exit 0

set -ex
export REGISTRY=${REGISTRY:-icr.io/codeengine}

# Create the app
ibmcloud ce app create -n cron-app --image ${REGISTRY}/cron --min-scale=1

# Setup the cron Event Source, send event every minute
ibmcloud ce sub cron create -n cron-sub -d cron-app \
  --data '{"mydata":"hello world"}' -s '* * * * *'

# Now wait until we get the event - shouldn't take more than a minute
while true ; do
  ibmcloud ce app logs --name cron-app > out
  grep "hello world" out > /dev/null 2>&1 && break
  sleep 10
done

echo "Log from 'cron-app' app:"
cat out

# Clean up
clean
