FROM icr.io/codeengine/golang:latest AS stage

ENV GOTOOLCHAIN auto

WORKDIR /app/src

COPY cmd/adapter/ ./adapter/

COPY go.mod .

COPY go.sum .

RUN CGO_ENABLED=0 GOOS=linux go build -o adapter ./adapter

FROM icr.io/codeengine/alpine

WORKDIR /app/src

COPY --from=stage /app/src/adapter/adapter .

CMD [ "./adapter" ]