#!/bin/bash

set -euo pipefail

# Env Vars:
# REGISTRY: name of the image registry/namespace to store the images
#
# NOTE: to run this you MUST set the REGISTRY environment variable to
# your own image registry/namespace otherwise the `docker push` commands
# will fail due to an auth failure. Which means, you also need to be logged
# into that registry before you run it.

export REGISTRY=${REGISTRY:-icr.io/codeengine}

# Build the images
docker build -f Dockerfile.client -t "${REGISTRY}"/grpc-client . --platform linux/amd64
docker build -f Dockerfile.server -t "${REGISTRY}"/grpc-server . --platform linux/amd64

# And push it
docker push "${REGISTRY}"/grpc-client
docker push "${REGISTRY}"/grpc-server
