FROM golang:latest AS stage

WORKDIR /app/src

COPY client/ ./client/

COPY ecommerce/ ./ecommerce/

COPY go.mod .

COPY go.sum .

RUN CGO_ENABLED=0 GOOS=linux go build -o client ./client

FROM golang:latest

WORKDIR /app/src

COPY --from=stage /app/src/client/client .

CMD [ "./client" ]