#!/bin/bash

set -eo pipefail

SERVER_APP_NAME="a-grpc-server"
CLIENT_APP_NAME="a-grpc-client"

# Clean up previous run
function clean() {
  echo "[INFO] Deleting CE client/server application ${CLIENT_APP_NAME}"
  ibmcloud ce app delete --name $CLIENT_APP_NAME --force --ignore-not-found > /dev/null 2>&1
  echo "[INFO] Deleting CE gRPC server application ${SERVER_APP_NAME}"
  ibmcloud ce app delete --name $SERVER_APP_NAME --force --ignore-not-found > /dev/null 2>&1
}

echo "[INFO] going to clean existing project resources"
clean

# In case this script has been executed with `./run clean`, we stop right after the cleanup
[[ "$1" == "clean" ]] && exit 0

# Create the gRPC server app
echo "[INFO] Creating CE gRPC server application ${SERVER_APP_NAME}"
ibmcloud ce app create --name "${SERVER_APP_NAME}" --port h2c:8080 --image icr.io/codeengine/grpc-server --min-scale 0

echo "[INFO] Retrieving gRPC server local endpoint"
SERVER_INTERNAL_ENDPOINT=$(ibmcloud ce app get -n "${SERVER_APP_NAME}" -o project-url | sed 's/http:\/\///')
echo "[INFO] Local endpoint is: ${SERVER_INTERNAL_ENDPOINT}"

# Create the client server app
echo "[INFO] Creating CE client/server application ${CLIENT_APP_NAME}"
ibmcloud ce app create --name "${CLIENT_APP_NAME}" --image icr.io/codeengine/grpc-client --min-scale 0 --env INSECURE=true --env ENDPOINT_WITH_PORT="${SERVER_INTERNAL_ENDPOINT}:80"

# Get the client server public endpoint
echo "[INFO] Retrieving client/server public endpoint"
URL=$(ibmcloud ce app get -n "${CLIENT_APP_NAME}" -o url)
echo "[INFO] Endpoint is: ${URL}"

# Query the list of groceries by food category
echo "[INFO] Retrieving available food items"
curl -q "${URL}"/listgroceries/food

# Buy an item from food and pay with 5.0 dollars
echo "[INFO] Going to buy an apple, paying with 5.0 dollars"
JSON_RESPONSE=$(curl -s "${URL}"/buygrocery/food/apple/5.0)
echo "${JSON_RESPONSE}"

# Validate payment operation
echo "[INFO] Validating payment operation state"
OPERATION_SUCCEEDED=$(echo "${JSON_RESPONSE}" | jq '.success')
if [ "${OPERATION_SUCCEEDED}" != "true" ]
then
    echo "[ERROR] Payment failed, bailing out."
    clean
    exit  1
fi

clean

echo "[INFO] Successful payment operation."
exit 0
