#!/bin/bash
set -eo pipefail

usage() {
  echo "Example usage: ./fleet_logs --tier <tier> --fleet-id <fleet-id> --task-id <task-id> --since 6h0m0s"
  exit 1
}

ICL_ENDPOINT="${LOGS_URL}"
REGION="${REGION:=eu-de}"
NAME_PREFIX="${NAME_PREFIX:=ce-fleet-sandbox}"
RESOURCE_GROUP="${RESOURCE_GROUP:=$NAME_PREFIX--rg}"
ICL_NAME="${NAME_PREFIX}--icl"
FLEET_ID=
TASK_ID=
SUBCOMPONENT_TYPE=
TIER="frequent_search"
OUTPUT="logs-raw"
SINCE="6h0m0s"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

while [[ $# -gt 0 ]]; do
  case "$1" in
    --fleet-id)
      shift
      FLEET_ID="$1"
      ;;

    --task-id)
      shift
      TASK_ID="$1"
      ;;

    --subcomponent-type)
      shift
      SUBCOMPONENT_TYPE="$1"
      ;;

    --tier)
      shift
      TIER="$1"
      ;;

    --output)
      shift
      OUTPUT="$1"
      ;;

    --since)
      shift
      SINCE="$1"
      ;;

    --help)
      usage
      ;;

    *)
      usage
      ;;
  esac
  shift
done

source ${SCRIPT_DIR}/common.sh

target_region $REGION > /dev/null
target_resource_group $RESOURCE_GROUP > /dev/null

ibmcloud plugin show logs > /dev/null

if [[ $? -ne 0 ]]; then
    ibmcloud plugin install logs
fi

if [[ -z "${ICL_ENDPOINT}" ]]; then
  ICL_ENDPOINT=https://"$(ibmcloud resource service-instance ${ICL_NAME} -o json | jq -r '.[].extensions.external_api')"
fi

LOGS_FILTER="source logs"
if [ -n "$FLEET_ID" ]; then
    LOGS_FILTER="${LOGS_FILTER} | filter \$d.codeengine.fleetId ~ '${FLEET_ID}'"
fi
if [ -n "$TASK_ID" ]; then
    LOGS_FILTER="${LOGS_FILTER} | filter \$d.codeengine.taskId ~ '${TASK_ID}'"
fi
if [ -n "$SUBCOMPONENT_TYPE" ]; then
    LOGS_FILTER="${LOGS_FILTER} | filter \$d.codeengine.subcomponentType ~ '${SUBCOMPONENT_TYPE}'"
fi

ibmcloud logs query --since ${SINCE} --tier ${TIER} --query "${LOGS_FILTER} | sort by \$m.timestamp" --service-url "${ICL_ENDPOINT}" --output ${OUTPUT}
