#!/bin/sh
REGION="${REGION:=eu-de}"
NAME_PREFIX="${NAME_PREFIX:=ce-fleet-sandbox}"
RESOURCE_GROUP="${RESOURCE_GROUP:=$NAME_PREFIX--rg}"

ibmcloud login --sso -r "$REGION" -g "$RESOURCE_GROUP"


ibmcloud ce project select --name "${NAME_PREFIX}--ce-project"

