#!/usr/bin/env bash
set -eu

truncate -s0 commands.jsonl

batch_size=1000
idx=0
batch_idx=0

# clean previous batches
rm -f ../../data/input/inferencing/batches/*.txt

for f in ../../data/input/inferencing/recipes/*.json; do
  idx=$(( idx + 1 ))
  if (( idx % batch_size == 0 )); then
    echo "{\"cmds\": [\"python\", \"app.py\"], \"args\": [\"/input/batches/$batch_idx.txt\"]}" >> commands.jsonl
    batch_idx=$(( batch_idx + 1 ))
  fi

  file_in=$(basename "$f")

  # echo "batch=$batch_idx idx=$idx file=$f"
  echo "/input/recipes/${file_in}" >> "../../data/input/inferencing/batches/$batch_idx.txt"

done

echo "{\"cmds\": [\"python\", \"app.py\"], \"args\": [\"/input/batches/$batch_idx.txt\"]}" >> commands.jsonl
