#!/bin/bash

set -e

uuid=$(uuidgen | tr '[:upper:]' '[:lower:]' | awk -F- '{print $1}')

IMAGE=$(ibmcloud cr images | grep "ce--fleet-inferencing" | awk '{print $1}')

if [ -z "${IMAGE}" ]; then
  echo "no image found. pls build a inferencing image with ./build"
  exit -1
fi

# getting the automatically created registry secret, e.g. ce-auto-icr-private-<region>
REGION=$(ibmcloud target -o json | jq -r '.region.name')
REGISTRY_SECRET_NAME="ce-auto-icr-private-$REGION"

PRIVATE_IMAGE="private.$IMAGE"

echo ibmcloud code-engine fleet create --name "fleet-${uuid}-1"
echo "  " --tasks-state-store fleet-task-store
echo "  " --subnetpool-name fleet-subnetpool
echo "  " --image $PRIVATE_IMAGE
echo "  " --registry-secret $REGISTRY_SECRET_NAME
echo "  " --max-scale 8
echo "  " --tasks-from-local-file commands_h100.jsonl
echo "  " --gpu h100:1
echo "  " --cpu 20
echo "  " --memory 200G
echo "  " --env HUGGINGFACEHUB_API_TOKEN="REDACTED"
echo "  " --env PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"
echo "  " --env MODEL_NAME="ibm-granite/granite-4.0-micro"
echo "  " --mount-data-store /root/.cache/huggingface=fleet-input-store:/huggingface
echo "  " --mount-data-store /input=fleet-input-store:/inferencing
echo "  " --mount-data-store /output=fleet-output-store:/inferencing

ibmcloud code-engine fleet create --name "fleet-${uuid}-1" \
--tasks-state-store fleet-task-store \
--subnetpool-name fleet-subnetpool \
--image $PRIVATE_IMAGE \
--registry-secret $REGISTRY_SECRET_NAME \
--max-scale 8 \
--tasks-from-local-file commands_h100.jsonl \
--gpu h100:1 \
--cpu 20 \
--memory 200G \
--env HUGGINGFACEHUB_API_TOKEN="$HUGGINGFACEHUB_API_TOKEN" \
--env PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True" \
--env MODEL_NAME="ibm-granite/granite-4.0-micro" \
--mount-data-store /root/.cache/huggingface=fleet-input-store:/huggingface \
--mount-data-store /input=fleet-input-store:/inferencing \
--mount-data-store /output=fleet-output-store:/inferencing


