#!/bin/bash

# Env Vars:
# REPOSITORY: name of the image registry/namespace to get the images
# COS_ID: If set, specifies the full CRN of a Cloud Object Storage instance to
# use

export REPOSITORY=${REPOSITORY:-ibmcom}
export PROJECT_NAME=$(ibmcloud ce project current | \
  awk -F: '/Project Name/{ print $2 }')
export PROJECT_ID=$(ibmcloud ce project get --name ${PROJECT_NAME} | \
  awk '/^ID/{ print $2 }')
export POLICY_ID=""

# Clean up previous run
function clean() {
  set +x
  echo "Cleaning..."

  # Delete the event subscription
  ibmcloud ce sub cos delete -n cos-sub -f --wait=true > /dev/null 2>&1 || true

  # Delete the IAM auth policy
  if [[ -n "$POLICY_ID" ]]; then
    ibmcloud iam authorization-policy-delete $POLICY --force \
	  > /dev/null 2>&1 || true
  fi

  # Delete the app
  ibmcloud ce app delete --name cos-app --force > /dev/null 2>&1 || true

  # Delete the COS bucket
  ibmcloud cos bucket-delete --bucket ${PROJECT_ID} --force \
    > /dev/null 2>&1 || true

  # Delete the COS instance unless the instance was given to us
  if [[ -z "$COS_ID" ]]; then
    ibmcloud resource service-instance-delete codeengine-cos -f -q \
	  > /dev/null 2>&1 || true
  fi

  rm -f out
}

clean
[[ "$1" == "clean" ]] && exit 0

set -ex

CID=${COS_ID}

# Create a COS instance unless one has been specified for use
if [[ $CID == "" ]]; then
  ibmcloud resource service-instance-create codeengine-cos \
    cloud-object-storage lite global
  CID=$(ibmcloud resource service-instance codeengine-cos | \
    awk '/^ID/{ print $2 }')
fi

# Set the COS config to use this instance
ibmcloud cos config crn --crn $CID --force
ibmcloud cos config auth --method IAM

# Create IAM authorization policy so we can receive notifications from COS
POLICY_ID=$(ibmcloud iam authorization-policy-create codeengine \
 cloud-object-storage "Notifications Manager" \
 --source-service-instance-name ${PROJECT_NAME} \
 --target-service-instance-id ${CID} | awk '/^Authorization/{ print $3 }')

# Create our bucket
export BUCKET=${PROJECT_ID}
ibmcloud cos bucket-create --bucket ${BUCKET} --ibm-service-instance-id $CID

# Create the app && save its URL for later
ibmcloud ce app create -n cos-app --image ${REPOSITORY}/cos-listen \
  --min-scale=1 --max-scale=1
URL=$(ibmcloud ce app get --output jsonpath='{.status.url}' --name cos-app)

# Setup the COS Event Source
ibmcloud ce sub cos create -n cos-sub -d cos-app -b ${BUCKET}

# Extract the instance name from `ibmcloud ce app get`
INSTANCE=$(ibmcloud ce app get --name cos-app| awk '/cos.*Running/{ print $1 }')
echo Instance name: $INSTANCE

# Now wait until we get the event - shouldn't take more than a minute
while true ; do
  # Upload a file to COS (this will generate an event)
  ibmcloud cos object-put --bucket ${BUCKET} --key "README.md" --body README.md

  # Delete the file from COS (another event)
  ibmcloud cos object-delete --bucket ${BUCKET} --key "README.md" --force

  ibmcloud ce app logs --instance $INSTANCE > out
  grep "README.md" out > /dev/null 2>&1 && break
  sleep 10
done

echo "Log from 'cos-app' app:"
cat out

echo "=============="
echo "Event stats:"

curl -Ls ${URL}/stats

# Clean up
clean
