#!/bin/bash

# Define our ICR Namespace env var for later use
ID=$(ibmcloud ce project current | sed -n "s/^Subdomain: *\([^ ]*\).*$/\1/p")
ICR_NS=s2i-b-${ID:1:12}

# Clean up previous run
function clean() {
  set +ex
  echo Cleaning...
  (
  ibmcloud cr namespace-rm "${ICR_NS}" -f
  ibmcloud ce app delete -n s2i-bapp -f
  ibmcloud ce registry delete -n s2i-bicr -f
  ibmcloud ce buildrun delete -n s2i-brun -f
  ibmcloud ce build delete -n s2i-bbuild -f
  ibmcloud iam api-keys | grep s2i-bapi | sed "s/.*\(ApiKey\)/\1/" | while read a
  do
	ibmcloud iam api-key-delete -f $a
  done
  rm -f out .ce-reg-secret || true
  ) > /dev/null 2>&1
}

clean
[[ "$1" == "clean" ]] && exit 0

# Grab the ICR server location based no our region
export ICR=$(ibmcloud cr info | sed -n 's/.*Registry   *\(.*icr.io\).*/\1/p')

set -ex

# Create an ICR namespace to hold our new image
ibmcloud cr namespace-add $ICR_NS

# Create an apikey, put it in a registry secret. Used to push/pull image to ICR
ibmcloud iam api-key-create s2i-bapi | \
  grep "API Key" | sed 's/^.*Key  *//' | sed "s/ *$//" > .ce-reg-secret
ibmcloud ce registry create -n s2i-bicr -s $ICR -u iamapikey \
  --password-from-file .ce-reg-secret

# Define the build of this dir in this github repo
ibmcloud ce build create -n s2i-bbuild -i "$ICR/${ICR_NS}/app" --rs s2i-bicr \
  --source https://github.com/IBM/CodeEngine --context-dir s2i-buildpacks \
  --strategy buildpacks

# Now kick off the build itself
ibmcloud ce buildrun submit -n s2i-brun --build s2i-bbuild --wait

# Test the image we just built - deploy an app and 'curl' it
ibmcloud ce app create -n s2i-bapp --image "$ICR/${ICR_NS}/app" --rs s2i-bicr
URL=$(ibmcloud ce app get -n s2i-bapp -o url)
curl -fs "${URL}" | tee out
[[ "${PIPESTATUS[0]}" == "0" ]]

if ! grep "I was built"  out > /dev/null ; then
  echo "Missing expected outout"
  exit 1
fi

# Clean
clean
