#!/usr/bin/env bash

# Env Vars:
# REGISTRY: name of the image registry/namespace to store the images
#
# NOTE: to run this you MUST set the REGISTRY environment variable to
# your own image registry/namespace otherwise the `docker push` commands
# will fail due to an auth failure. Which means, you also need to be logged
# into that registry before you run it.


set -ex
export REGISTRY=${REGISTRY:-icr.io/codeengine}

# Build the job image and push it
docker build -t "${REGISTRY}"/job2vsi -f Dockerfile .
docker push "${REGISTRY}"/job2vsi
