#!/bin/bash

# Env Vars:
# REGISTRY: name of the image registry/namespace to get the images

# Clean up previous run
function clean() {
  set +ex
  echo Cleaning... 
  (
  ibmcloud ce sub ping delete -n ping-sub -f --wait=true
  ibmcloud ce app delete -n ping-app -f
  rm -f out
  ) > /dev/null 2>&1
}

clean
[[ "$1" == "clean" ]] && exit 0

set -ex
export REGISTRY=${REGISTRY:-ibmcom}

# Create the app
ibmcloud ce app create -n ping-app --image ${REGISTRY}/ping --min-scale=1

# Setup the Ping (cron) Event Source, send event every minute
ibmcloud ce sub ping create -n ping-sub -d ping-app \
  --data '{"mydata":"hello world"}' -s '* * * * *'

# Extract the instance name from `ibmcloud ce app get`
name=$(ibmcloud ce app get -n ping-app | awk '/ping.*Running/{ print $1 }')
echo Instance name: $name

# Now wait until we get the event - shouldn't take more than a minute
while true ; do
  ibmcloud ce app logs --instance $name > out
  grep "hello world" out > /dev/null 2>&1 && break
  sleep 10
done

echo "Log from 'ping-app' app:"
cat out

# Clean up
clean
