#!/bin/bash

# Env Vars:
# REPOSITORY: name of the image registry/namespace to get the images

# Clean up previous run
function clean() {
  set +x
  echo Cleaning...
  ic ce app delete -n mapenv -f --wto=0 > /dev/null 2>&1 || true
  ic ce secret delete -n mysecret -f > /dev/null 2>&1 || true
  ic ce configmap delete -n myconfig -f > /dev/null 2>&1 || true
  rm -f out
}

clean
[[ "$1" == "clean" ]] && exit 0

set -ex
export REPOSITORY=${REPOSITORY:-ibmcom}

# Create a Secret and a ConfigMap
ic ce secret create --name mysecret --from-literal MY_SECRET_APIKEY=letmein
ic ce configmap create --name myconfig --from-literal MY_CONFIG_KNOB=42

# Create the app
ic ce app create -n mapenv --image ${REPOSITORY}/mapenv \
  --env-from-secret mysecret --env-from-configmap myconfig

# Get the URL of the app for later use
URL=$(ic ce app get -n mapenv -o jsonpath={.status.url})

# Just force it to log something by hitting ig
curl -Ls $URL

# Extract the instance name from `ic ce app get`
ic ce app get -n mapenv | tee out
name=$(grep "mapenv.*Running" out | tail -1 | sed "s/ [12].*//")
echo Instance name: $name

# Now wait check the logs to see if the env vars were set
ic ce app logs --instance $name | tee out
grep MY_ out

# Clean up
clean
