#!/bin/bash

set -e

uuid=$(uuidgen | tr '[:upper:]' '[:lower:]' | awk -F- '{print $1}')

IMAGE="quay.io/docling-project/docling-serve-cpu"

echo ibmcloud code-engine beta fleet create --name "fleet-${uuid}-1"
echo "  "--image $IMAGE
echo "  "--registry-secret fleet-registry-secret
echo "  "--worker-profile mx3d-24x240
echo "  "--max-scale 4
echo "  "--tasks-from-local-file commands.jsonl
echo "  "--cpu 24
echo "  "--memory 120G
echo "  "--mount-data-store /input=fleet-input-store:/docling
echo "  "--mount-data-store /output=fleet-output-store:/docling

ibmcloud code-engine beta fleet create --name "fleet-${uuid}-1" \
--image $IMAGE \
--registry-secret fleet-registry-secret \
--worker-profile mx3d-24x240 \
--max-scale 4 \
--tasks-from-local-file commands.jsonl \
--cpu 24 \
--memory 240G \
--tasks-state-store fleet-task-store \
--mount-data-store /input=fleet-input-store:/docling \
--mount-data-store /output=fleet-output-store:/docling
