#!/bin/bash

set -e

uuid=$(uuidgen | tr '[:upper:]' '[:lower:]' | awk -F- '{print $1}')

IMAGE=$(ibmcloud cr images | grep "ce--fleet-pyscf" | awk '{print $1}')

if [ -z "${IMAGE}" ]; then
  echo "no image found. pls build a pyscf image with ./build"
  exit -1
fi

MAX_SCALE=1
PROFILE="mx2-4x32"
CPU=4
MEMORY=32G

echo ibmcloud code-engine experimental fleet run 
echo "  "--name "fleet-${uuid}-1" 
echo "  "--image $IMAGE 
echo "  "--tasks-from-file commands.jsonl
echo "  "--cpu $CPU
echo "  "--memory $MEMORY
echo "  "--max-scale $MAX_SCALE
echo "  "--worker-profile $PROFILE

ibmcloud code-engine experimental fleet run --name "fleet-${uuid}-1" --image $IMAGE --registry-secret fleet-registry-secret --worker-profile $PROFILE --max-scale $MAX_SCALE --cpu $CPU --memory $MEMORY --env OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 -env OMPI_ALLOW_RUN_AS_ROOT=1 --tasks-from-file commands.jsonl


