#!/bin/bash

# Env Vars:
# REPOSITORY: name of the image registry/namespace to store the images
# NOCACHE: set this to "--no-cache" to turn off the Docker build cache
#
# NOTE: to run this you MUST set the REPOSITORY environment variable to
# your own image registry/namespace otherwise the `docker push` commands
# will fail due to an auth failure. Which means, you also need to be logged
# into that registry before you run it.

set -ex
export REGISTRY=${REGISTRY:-icr.io/codeengine}

# Build the image
docker build ${NOCACHE} -t ${REGISTRY}/cos2cos . --platform linux/amd64

# And push it
docker push ${REGISTRY}/cos2cos
