#!/bin/bash

# Env Vars:
# REPOSITORY: name of the image registry/namespace to store the images
#
# NOTE: to run this you MUST set the REPOSITORY environment variable to
# your own image registry/namespace otherwise the `docker push` commands
# will fail due to an auth failure. Which means, you also need to be logged
# into that registry before you run it.

set -ex
export REPOSITORY=${REPOSITORY:-ibmcom}

# Build the image
docker build -t ${REPOSITORY}/cecli .

# And push it
docker push ${REPOSITORY}/cecli
