#!/bin/bash

# Env Vars:
# REGISTRY: name of the image registry/namespace to store the images
# NOCACHE: set this to "--no-cache" to turn off the Docker build cache
#
# NOTE: to run this you MUST set the REGISTRY environment variable to
# your own image registry/namespace otherwise the `docker push` commands
# will fail due to an auth failure. Which means, you also need to be logged
# into that registry before you run it.

set -ex
export REGISTRY=${REGISTRY:-icr.io/codeengine}

# First build the app's image and push it
docker build ${NOCACHE} -t ${REGISTRY}/a2j-app -f Dockerfile.app . --platform linux/amd64
docker push ${REGISTRY}/a2j-app

# Now build the job's
docker build ${NOCACHE} -t ${REGISTRY}/a2j-job -f Dockerfile.job . --platform linux/amd64
docker push ${REGISTRY}/a2j-job
