#!/bin/bash

# Env Vars:
# REPOSITORY: name of the image registry/namespace to store the images

set -ex
export REPOSITORY=${REPOSITORY:-ibmcom}

# First build the app's image and push it
docker build -t ${REPOSITORY}/a2j-app -f Dockerfile.app .
docker push ${REPOSITORY}/a2j-app

# Now build the job's
docker build -t ${REPOSITORY}/a2j-job -f Dockerfile.job .
docker push ${REPOSITORY}/a2j-job
