#!/bin/bash

# Env Vars:
# COUNT: number of instances of the job to run
# REPOSITORY: name of the image registry/namespace to get the images

# Clean up previous run
function clean() {
  set +x
  echo Cleaning...
  ibmcloud ce job delete -n a2j-job -f > /dev/null 2>&1 || true
  ibmcloud ce app delete -n a2j-app -f --wto=0 > /dev/null 2>&1 || true
  rm -f out
}

clean
[[ "$1" == "clean" ]] && exit 0

set -ex
export REPOSITORY=${REPOSITORY:-ibmcom}
export COUNT=${COUNT:-50}

# Create the app
ibmcloud ce app create -n a2j-app --image ${REPOSITORY}/a2j-app

# Get metadata about the app for later use
URL=$(ibmcloud ce app get -n a2j-app -o jsonpath={.status.url})

# Create the job definition
ibmcloud ce job create -n a2j-job --ai=1-${COUNT} --image ${REPOSITORY}/a2j-job

# Now, curl the app and see if it creates the job
curl -s ${URL}/a2j-job -X PUT | tee out
jobrun=$(cat out)

while ! ibmcloud ce jobrun get -n ${jobrun} | grep "Succeeded.*${COUNT}" ; do
  sleep 2
done

# Verify job ran ok
ibmcloud ce jobrun logs -i ${jobrun}-${COUNT}-0 | grep "JOB_INDEX.*${COUNT}"

# Clean up
clean
