#!/bin/bash

set -e

uuid=$(uuidgen | tr '[:upper:]' '[:lower:]' | awk -F- '{print $1}')

IMAGE=$(ibmcloud cr images | grep "ce--fleet-montecarlo" | awk '{print $1}')

if [ -z "${IMAGE}" ]; then
  echo "no image found. pls build a montecarlo image with ./build.sh"
  exit -1
fi

MAX_SCALE=24
PROFILE="mx2-4x32"
CPU=1
MEMORY=8G

echo ibmcloud code-engine experimental fleet run 
echo "  "--name "fleet-${uuid}-1" 
echo "  "--image $IMAGE 
echo "  "--tasks-from-file commands.jsonl
echo "  "--cpu $CPU
echo "  "--memory $MEMORY
echo "  "--max-scale $MAX_SCALE


ibmcloud code-engine experimental fleet run --name "fleet-${uuid}-1" --image $IMAGE --registry-secret fleet-registry-secret --worker-profile $PROFILE --max-scale $MAX_SCALE --cpu $CPU --memory $MEMORY --tasks-from-file commands.jsonl


