FROM icr.io/codeengine/golang:alpine AS bootstrap
WORKDIR /go/src/
COPY . .
RUN go build -o /sender sender.go

# Copy the exe into a smaller base image
# IMPORTANT - make sure we add in SSL certs otherwise we won't be able
# to talk to Event Steams via TLS
FROM icr.io/codeengine/alpine
RUN apk add ca-certificates
COPY --from=bootstrap /sender /sender
ENTRYPOINT ["/sender"]
