#!/bin/bash

set -e

# Replace all "CE_SUBDOMAIN" in the config file with the Code Engine subdomain (k8s ns)
# see: https://www.baeldung.com/linux/nginx-config-environment-variables
echo "Performing environment variable substitutions ..."
envsubst '\$JUPYTER_NOTEBOOK_APP_FQDN \$JUPYTER_NOTEBOOK_APP_NAME \$JUPYTER_AUTH_APP_NAME \$CE_SUBDOMAIN' < /tmp/jupyter-template.conf > /opt/app-root/etc/nginx.d/jupyter.conf

echo "Starting NGINX with the following config file '${NGINX_CONF_PATH}'"
cat ${NGINX_CONF_PATH}

echo "Using following config '/opt/app-root/etc/nginx.d/jupyter.conf' to expose the jupyter notebook:"
cat /opt/app-root/etc/nginx.d/jupyter.conf

# Now run nginx
echo "Launching NGINX..."
nginx -g 'daemon off;'