#!/bin/bash

# Env Vars:
# REPOSITORY: name of the image registry/namespace to store the images

set -ex
export REPOSITORY=${REPOSITORY:-ibmcom}

# First build the app's image and push it
docker build -t ${REPOSITORY}/bind-app -f Dockerfile .
docker push ${REPOSITORY}/bind-app
