#!/bin/bash

# Env Vars:
# REPOSITORY: name of the image registry/namespace to get the images

# Clean up previous run
function clean() {
  set +x
  echo Cleaning...
  ibmcloud ce app delete -n ba-app -f --wto=0 > /dev/null 2>&1 || true
  ibmcloud resource service-instance-delete ba-db -f > /dev/null 2>&1 || true
  rm -f out
}

clean

[[ "$1" == "clean" ]] && exit 0

set -ex
export REPOSITORY=${REPOSITORY:-ibmcom}

# Create an instance of DB2
ibmcloud resource service-instance-create ba-db dashdb-for-transactions free us-south

# Create the app
ibmcloud ce app create -n ba-app --image ${REPOSITORY}/bind-app

# Get the URL of the app for later use
URL=$(ibmcloud ce app get -n ba-app -o jsonpath={.status.url})

# Bind the service credentials to the app
ibmcloud ce app bind --name ba-app --service-instance ba-db

# Curl the app to make sure it had the creds
curl -Ls ${URL} | tee out

if ! grep VCAP_SERVICES out > /dev/null ; then
  echo "Missing VCAP_SERVICES in App's env vars"
  exit 1
fi

# Clean up
clean
