FROM golang:alpine
# Need git so the "go get" cand download the needed packages
RUN apk add --no-cache git
COPY client.go /src/
WORKDIR /src
RUN go get -d .
RUN go build -o /client client.go

# Copy the exe into a smaller base image
FROM alpine
COPY --from=0 /client /client
ENTRYPOINT [ "/client" ]
