#!/bin/sh
REGION="${REGION:=eu-de}"
NAME_PREFIX="${NAME_PREFIX:=ce-fleet-sandbox}"

ibmcloud login --sso -r "$REGION" -g "${NAME_PREFIX}--rg"


ibmcloud ce project select --name "${NAME_PREFIX}--ce-project"

