#!/bin/bash

set -e

uuid=$(uuidgen | tr '[:upper:]' '[:lower:]' | awk -F- '{print $1}')

TASKS=10000
MAX_SCALE=512
PROFILE="bx2-16x64"
SLEEP="3"

echo ibmcloud code-engine experimental fleet run 
echo "  " --name "fleet-${uuid}-1"
echo "  " --image registry.access.redhat.com/ubi8/ubi-minimal:latest
echo "  " --registry-secret fleet-registry-secret 
echo "  " --command="sleep"
echo "  " --arg "$SLEEP"
echo "  " --tasks $TASKS
echo "  " --cpu 1 
echo "  " --memory 4G
echo "  " --max-scale $MAX_SCALE
echo "  " --worker-profile $PROFILE

ibmcloud code-engine experimental fleet run --name "fleet-${uuid}-1" --image registry.access.redhat.com/ubi8/ubi-minimal:latest --registry-secret fleet-registry-secret --worker-profile $PROFILE --max-scale $MAX_SCALE --command="sleep" --arg "$SLEEP" --tasks $TASKS --cpu 1 --memory 4G



