#!/bin/bash

set -e

uuid=$(uuidgen | tr '[:upper:]' '[:lower:]' | awk -F- '{print $1}')

TASKS=100
MAX_SCALE=10
PROFILE=cx2-2x4
CPU=1
MEMORY=2G

echo ibmcloud code-engine experimental fleet run 
echo "  "--name "fleet-${uuid}-1"
echo "  "--image registry.access.redhat.com/ubi8/ubi-minimal:latest
echo "  "--registry-secret fleet-registry-secret
echo "  "--worker-profile $PROFILE
echo "  "--command="sleep" 
echo "  "--arg "2"
echo "  "--tasks $TASKS
echo "  "--cpu $CPU
echo "  "--memory $MEMORY
echo "  "--max-scale $MAX_SCALE 

ibmcloud code-engine experimental fleet run --name "fleet-${uuid}-1" --image registry.access.redhat.com/ubi8/ubi-minimal:latest --registry-secret fleet-registry-secret --worker-profile $PROFILE --max-scale $MAX_SCALE --command="sleep" --arg "2" --tasks $TASKS --cpu $CPU --memory $MEMORY


